// AUTO-GENERE - metadonnees des 101 ecrans IzenRide.
export type ScreenMeta = { id: string; title: string; catKey: string; catLabel: string; comp: string };
export const SCREENS: ScreenMeta[] = [
  { id: '000', title: 'Splash', catKey: 'auth', catLabel: 'Onboarding & Connexion', comp: 'SplashScreen' },
  { id: '001', title: 'Onboarding-1 Bienvenue', catKey: 'auth', catLabel: 'Onboarding & Connexion', comp: 'Onboarding1BienvenueScreen' },
  { id: '002', title: 'Onboarding-3 Présentation événements et marketplace', catKey: 'auth', catLabel: 'Onboarding & Connexion', comp: 'Onboarding3PresentationEvenementsEtMarketplaceScreen' },
  { id: '003', title: 'Onboarding-4 Demande permissions localisation notifs contacts', catKey: 'auth', catLabel: 'Onboarding & Connexion', comp: 'Onboarding4DemandePermissionsLocalisationNotifsContactsScreen' },
  { id: '004', title: 'Propagation thème ultra-dark', catKey: 'auth', catLabel: 'Onboarding & Connexion', comp: 'PropagationThemeUltraDarkScreen' },
  { id: '005', title: 'Skeleton loaders 5 écrans', catKey: 'auth', catLabel: 'Onboarding & Connexion', comp: 'SkeletonLoaders5EcransScreen' },
  { id: '006', title: 'Inscription', catKey: 'auth', catLabel: 'Onboarding & Connexion', comp: 'InscriptionScreen' },
  { id: '007', title: 'Login connexion', catKey: 'auth', catLabel: 'Onboarding & Connexion', comp: 'LoginConnexionScreen' },
  { id: '008', title: 'SSO loading state', catKey: 'auth', catLabel: 'Onboarding & Connexion', comp: 'SSOLoadingStateScreen' },
  { id: '009', title: 'Vérification SMS', catKey: 'auth', catLabel: 'Onboarding & Connexion', comp: 'VerificationSMSScreen' },
  { id: '010', title: 'Vérification email', catKey: 'auth', catLabel: 'Onboarding & Connexion', comp: 'VerificationEmailScreen' },
  { id: '011', title: 'Vérification email succès', catKey: 'auth', catLabel: 'Onboarding & Connexion', comp: 'VerificationEmailSuccesScreen' },
  { id: '012', title: 'Mot de passe oublié saisie email', catKey: 'auth', catLabel: 'Onboarding & Connexion', comp: 'MotDePasseOublieSaisieEmailScreen' },
  { id: '013', title: 'Mot de passe oublié confirmation', catKey: 'auth', catLabel: 'Onboarding & Connexion', comp: 'MotDePasseOublieConfirmationScreen' },
  { id: '014', title: 'Reset password nouveau mot de passe', catKey: 'auth', catLabel: 'Onboarding & Connexion', comp: 'ResetPasswordNouveauMotDePasseScreen' },
  { id: '015', title: 'Écran si l utilisateur refuse la géoloc', catKey: 'auth', catLabel: 'Onboarding & Connexion', comp: 'EcranSiLUtilisateurRefuseLaGeolocScreen' },
  { id: '016', title: 'Carte accueil', catKey: 'map', catLabel: 'Carte & GPS', comp: 'CarteAccueilScreen' },
  { id: '017', title: 'Gps', catKey: 'map', catLabel: 'Carte & GPS', comp: 'GpsScreen' },
  { id: '018', title: 'Recalcul d itinéraire', catKey: 'map', catLabel: 'Carte & GPS', comp: 'RecalculDItineraireScreen' },
  { id: '019', title: 'Mode hors-ligne', catKey: 'map', catLabel: 'Carte & GPS', comp: 'ModeHorsLigneScreen' },
  { id: '020', title: 'Migration Google MapLibre', catKey: 'map', catLabel: 'Carte & GPS', comp: 'MigrationGoogleMapLibreScreen' },
  { id: '021', title: 'Lieux favoris', catKey: 'map', catLabel: 'Carte & GPS', comp: 'LieuxFavorisScreen' },
  { id: '022', title: 'Historique de trajets', catKey: 'map', catLabel: 'Carte & GPS', comp: 'HistoriqueDeTrajetsScreen' },
  { id: '023', title: 'Détail d un trajet enregistré', catKey: 'map', catLabel: 'Carte & GPS', comp: 'DetailDUnTrajetEnregistreScreen' },
  { id: '024', title: 'Swipe-stack', catKey: 'match', catLabel: 'Rencontres', comp: 'SwipeStackScreen' },
  { id: '025', title: 'Match-filters', catKey: 'match', catLabel: 'Rencontres', comp: 'MatchFiltersScreen' },
  { id: '026', title: 'Filtres de matching', catKey: 'match', catLabel: 'Rencontres', comp: 'FiltresDeMatchingScreen' },
  { id: '027', title: 'Recherche avancée filtres', catKey: 'match', catLabel: 'Rencontres', comp: 'RechercheAvanceeFiltresScreen' },
  { id: '028', title: 'Match-success', catKey: 'match', catLabel: 'Rencontres', comp: 'MatchSuccessScreen' },
  { id: '029', title: 'Super Like animation', catKey: 'match', catLabel: 'Rencontres', comp: 'SuperLikeAnimationScreen' },
  { id: '030', title: 'Qui m a liké premium', catKey: 'match', catLabel: 'Rencontres', comp: 'QuiMALikePremiumScreen' },
  { id: '031', title: 'Système Elle parle en premier', catKey: 'match', catLabel: 'Rencontres', comp: 'SystemeElleParleEnPremierScreen' },
  { id: '032', title: 'Profil détaillé d un autre rider', catKey: 'match', catLabel: 'Rencontres', comp: 'ProfilDetailleDUnAutreRiderScreen' },
  { id: '033', title: 'Unmatch', catKey: 'match', catLabel: 'Rencontres', comp: 'UnmatchScreen' },
  { id: '034', title: 'Aucun résultat de recherche', catKey: 'match', catLabel: 'Rencontres', comp: 'AucunResultatDeRechercheScreen' },
  { id: '035', title: 'Messages', catKey: 'messages', catLabel: 'Messages', comp: 'MessagesScreen' },
  { id: '036', title: 'Conversation 1-1', catKey: 'messages', catLabel: 'Messages', comp: 'Conversation11Screen' },
  { id: '037', title: 'Conversation bloquée archivée', catKey: 'messages', catLabel: 'Messages', comp: 'ConversationBloqueeArchiveeScreen' },
  { id: '038', title: 'Chat de groupe événement', catKey: 'messages', catLabel: 'Messages', comp: 'ChatDeGroupeEvenementScreen' },
  { id: '039', title: 'Empty state chat aucun match', catKey: 'messages', catLabel: 'Messages', comp: 'EmptyStateChatAucunMatchScreen' },
  { id: '040', title: 'Agenda accueil', catKey: 'events', catLabel: 'Agenda & Événements', comp: 'AgendaAccueilScreen' },
  { id: '041', title: 'Fiche événement', catKey: 'events', catLabel: 'Agenda & Événements', comp: 'FicheEvenementScreen' },
  { id: '042', title: 'Inviter à un événement', catKey: 'events', catLabel: 'Agenda & Événements', comp: 'InviterAUnEvenementScreen' },
  { id: '043', title: 'Liste des participants', catKey: 'events', catLabel: 'Agenda & Événements', comp: 'ListeDesParticipantsScreen' },
  { id: '044', title: 'Album photos post-événement', catKey: 'events', catLabel: 'Agenda & Événements', comp: 'AlbumPhotosPostEvenementScreen' },
  { id: '045', title: 'Annulation d événement', catKey: 'events', catLabel: 'Agenda & Événements', comp: 'AnnulationDEvenementScreen' },
  { id: '046', title: 'Édition d événement admin', catKey: 'events', catLabel: 'Agenda & Événements', comp: 'EditionDEvenementAdminScreen' },
  { id: '047', title: 'Marketplace accueil', catKey: 'market', catLabel: 'Marketplace', comp: 'MarketplaceAccueilScreen' },
  { id: '048', title: 'Création d annonce', catKey: 'market', catLabel: 'Marketplace', comp: 'CreationDAnnonceScreen' },
  { id: '049', title: 'Édition annonce existante', catKey: 'market', catLabel: 'Marketplace', comp: 'EditionAnnonceExistanteScreen' },
  { id: '050', title: 'Annonces favorites', catKey: 'market', catLabel: 'Marketplace', comp: 'AnnoncesFavoritesScreen' },
  { id: '051', title: 'Profil vendeur public', catKey: 'market', catLabel: 'Marketplace', comp: 'ProfilVendeurPublicScreen' },
  { id: '052', title: 'Mes commandes acheteur', catKey: 'market', catLabel: 'Marketplace', comp: 'MesCommandesAcheteurScreen' },
  { id: '053', title: 'Mes ventes vendeur', catKey: 'market', catLabel: 'Marketplace', comp: 'MesVentesVendeurScreen' },
  { id: '054', title: 'Checkout paiement Stripe Connect', catKey: 'market', catLabel: 'Marketplace', comp: 'CheckoutPaiementStripeConnectScreen' },
  { id: '055', title: 'Order-confirmation', catKey: 'market', catLabel: 'Marketplace', comp: 'OrderConfirmationScreen' },
  { id: '056', title: 'Notation post-achat', catKey: 'market', catLabel: 'Marketplace', comp: 'NotationPostAchatScreen' },
  { id: '057', title: 'Profil accueil', catKey: 'profile', catLabel: 'Profil', comp: 'ProfilAccueilScreen' },
  { id: '058', title: 'Mon profil vue lecture', catKey: 'profile', catLabel: 'Profil', comp: 'MonProfilVueLectureScreen' },
  { id: '059', title: 'Edition profil', catKey: 'profile', catLabel: 'Profil', comp: 'EditionProfilScreen' },
  { id: '060', title: 'Ajouter une autre moto', catKey: 'profile', catLabel: 'Profil', comp: 'AjouterUneAutreMotoScreen' },
  { id: '061', title: 'Badges achievements', catKey: 'profile', catLabel: 'Profil', comp: 'BadgesAchievementsScreen' },
  { id: '062', title: 'Visualiseur photo plein écran', catKey: 'profile', catLabel: 'Profil', comp: 'VisualiseurPhotoPleinEcranScreen' },
  { id: '063', title: 'Gestion photos détaillée', catKey: 'profile', catLabel: 'Profil', comp: 'GestionPhotosDetailleeScreen' },
  { id: '064', title: 'Paywall Premium', catKey: 'premium', catLabel: 'Premium', comp: 'PaywallPremiumScreen' },
  { id: '065', title: 'Showcase features Premium', catKey: 'premium', catLabel: 'Premium', comp: 'ShowcaseFeaturesPremiumScreen' },
  { id: '066', title: 'Premium activé', catKey: 'premium', catLabel: 'Premium', comp: 'PremiumActiveScreen' },
  { id: '067', title: 'Abonnement actif', catKey: 'premium', catLabel: 'Premium', comp: 'AbonnementActifScreen' },
  { id: '068', title: 'Annulation abonnement', catKey: 'premium', catLabel: 'Premium', comp: 'AnnulationAbonnementScreen' },
  { id: '069', title: 'Centre de notifications', catKey: 'notifs', catLabel: 'Notifications', comp: 'CentreDeNotificationsScreen' },
  { id: '070', title: 'Empty state notifications 2', catKey: 'notifs', catLabel: 'Notifications', comp: 'EmptyStateNotifications2Screen' },
  { id: '071', title: 'Réglages notifications', catKey: 'notifs', catLabel: 'Notifications', comp: 'ReglagesNotificationsScreen' },
  { id: '072', title: 'Réglage fenêtres silencieuses', catKey: 'notifs', catLabel: 'Notifications', comp: 'ReglageFenetresSilencieusesScreen' },
  { id: '073', title: 'Bouton SOS détaillé', catKey: 'safety', catLabel: 'Sécurité & Modération', comp: 'BoutonSOSDetailleScreen' },
  { id: '074', title: 'SOS confirmation envoi', catKey: 'safety', catLabel: 'Sécurité & Modération', comp: 'SOSConfirmationEnvoiScreen' },
  { id: '075', title: 'Bloquer un utilisateur', catKey: 'safety', catLabel: 'Sécurité & Modération', comp: 'BloquerUnUtilisateurScreen' },
  { id: '076', title: 'Signaler un utilisateur', catKey: 'safety', catLabel: 'Sécurité & Modération', comp: 'SignalerUnUtilisateurScreen' },
  { id: '077', title: 'Niveau de protection harcèlement', catKey: 'safety', catLabel: 'Sécurité & Modération', comp: 'NiveauDeProtectionHarcelementScreen' },
  { id: '078', title: 'Statut modération message', catKey: 'safety', catLabel: 'Sécurité & Modération', comp: 'StatutModerationMessageScreen' },
  { id: '079', title: 'Compte suspendu', catKey: 'safety', catLabel: 'Sécurité & Modération', comp: 'CompteSuspenduScreen' },
  { id: '080', title: 'Compte banni définitivement', catKey: 'safety', catLabel: 'Sécurité & Modération', comp: 'CompteBanniDefinitivementScreen' },
  { id: '081', title: 'Paramètres Compte', catKey: 'settings', catLabel: 'Réglages & Légal', comp: 'ParametresCompteScreen' },
  { id: '082', title: 'Apparence', catKey: 'settings', catLabel: 'Réglages & Légal', comp: 'ApparenceScreen' },
  { id: '083', title: 'Langue de l app', catKey: 'settings', catLabel: 'Réglages & Légal', comp: 'LangueDeLAppScreen' },
  { id: '084', title: 'Confidentialité détaillé', catKey: 'settings', catLabel: 'Réglages & Légal', comp: 'ConfidentialiteDetailleScreen' },
  { id: '085', title: 'Gestion des consentements', catKey: 'settings', catLabel: 'Réglages & Légal', comp: 'GestionDesConsentementsScreen' },
  { id: '086', title: 'Granularité par catégorie', catKey: 'settings', catLabel: 'Réglages & Légal', comp: 'GranulariteParCategorieScreen' },
  { id: '087', title: 'Exporter mes données', catKey: 'settings', catLabel: 'Réglages & Légal', comp: 'ExporterMesDonneesScreen' },
  { id: '088', title: 'Supprimer mon compte', catKey: 'settings', catLabel: 'Réglages & Légal', comp: 'SupprimerMonCompteScreen' },
  { id: '089', title: 'CGU', catKey: 'settings', catLabel: 'Réglages & Légal', comp: 'CGUScreen' },
  { id: '090', title: 'Mentions légales', catKey: 'settings', catLabel: 'Réglages & Légal', comp: 'MentionsLegalesScreen' },
  { id: '091', title: 'Politique de confidentialité', catKey: 'settings', catLabel: 'Réglages & Légal', comp: 'PolitiqueDeConfidentialiteScreen' },
  { id: '092', title: 'Politique cookies traceurs', catKey: 'settings', catLabel: 'Réglages & Légal', comp: 'PolitiqueCookiesTraceursScreen' },
  { id: '093', title: 'À propos', catKey: 'settings', catLabel: 'Réglages & Légal', comp: 'AProposScreen' },
  { id: '094', title: 'Aide et support', catKey: 'settings', catLabel: 'Réglages & Légal', comp: 'AideEtSupportScreen' },
  { id: '095', title: 'Pas de connexion internet', catKey: 'system', catLabel: 'États & Erreurs', comp: 'PasDeConnexionInternetScreen' },
  { id: '096', title: 'Erreur serveur 500', catKey: 'system', catLabel: 'États & Erreurs', comp: 'ErreurServeur500Screen' },
  { id: '097', title: 'Maintenance programmée', catKey: 'system', catLabel: 'États & Erreurs', comp: 'MaintenanceProgrammeeScreen' },
  { id: '098', title: 'Force update version trop ancienne', catKey: 'system', catLabel: 'États & Erreurs', comp: 'ForceUpdateVersionTropAncienneScreen' },
  { id: '099', title: 'Rate limit quota dépassé', catKey: 'system', catLabel: 'États & Erreurs', comp: 'RateLimitQuotaDepasseScreen' },
  { id: '100', title: 'Paiement échoué', catKey: 'system', catLabel: 'États & Erreurs', comp: 'PaiementEchoueScreen' },
];

export const CATEGORIES: { key: string; label: string }[] = [
  { key: 'auth', label: 'Onboarding & Connexion' },
  { key: 'map', label: 'Carte & GPS' },
  { key: 'match', label: 'Rencontres' },
  { key: 'messages', label: 'Messages' },
  { key: 'events', label: 'Agenda & Événements' },
  { key: 'market', label: 'Marketplace' },
  { key: 'profile', label: 'Profil' },
  { key: 'premium', label: 'Premium' },
  { key: 'notifs', label: 'Notifications' },
  { key: 'safety', label: 'Sécurité & Modération' },
  { key: 'settings', label: 'Réglages & Légal' },
  { key: 'system', label: 'États & Erreurs' },
];